from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages

class GraphState(TypedDict):
    """
    Shared state that flows between all nodes in the graph.
    Every node can read and update these fields.
    """

    # The original question from the user
    question: str

    # Rewritten version of the question (better for search)
    rewritten_query: str

    # Top 5 chunks retrieved from ChromaDB
    retrieved_chunks: list[dict]

    # After relevance grading: only the relevant chunks
    filtered_chunks: list[dict]

    # "relevant" or "not_relevant"
    relevance_score: str

    # Final answer generated by Gemini
    answer: str

    # Source papers and pages used in the answer
    sources: list[str]

    # "grounded" or "not_grounded"
    hallucination_flag: str

    # Full conversation history (for memory)
    chat_history: Annotated[list, add_messages]

    retry_count: int